package postgres

import (
	"context"
	"fmt"
	"strings"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/jsi/ibs-doc-engine/internal/domain"
)

type FolderRepo struct {
	pool *pgxpool.Pool
}

func NewFolderRepo(pool *pgxpool.Pool) *FolderRepo {
	return &FolderRepo{pool: pool}
}

// EnsureFolderHierarchy creates the folder path /{lib}/{class}/{ownerID}/{attType}/
// and returns the leaf folder ID. Uses ON CONFLICT to be idempotent.
func (r *FolderRepo) EnsureFolderHierarchy(
	ctx context.Context,
	ownerClassLibrary, ownerClassName, ownerID, attachmentType string,
) (uuid.UUID, error) {
	segments := []string{ownerClassLibrary, ownerClassName, ownerID, attachmentType}
	var parentID *uuid.UUID
	var leafID uuid.UUID

	for i, seg := range segments {
		path := "/" + strings.Join(segments[:i+1], "/")

		query := `INSERT INTO folders (id, name, parent_id, path, owner_class_library, owner_class_name, owner_id, is_auto_generated)
			VALUES ($1, $2, $3, $4, $5, $6, $7, TRUE)
			ON CONFLICT (path) DO UPDATE SET updated_at = NOW()
			RETURNING id`

		newID := uuid.New()
		var folderOwnerID string
		if i >= 2 {
			folderOwnerID = ownerID
		}

		var folderID uuid.UUID
		err := r.pool.QueryRow(ctx, query,
			newID, seg, parentID, path,
			ownerClassLibrary, ownerClassName, folderOwnerID,
		).Scan(&folderID)
		if err != nil {
			return uuid.Nil, fmt.Errorf("folder repo: ensure folder %q: %w", path, err)
		}

		parentID = &folderID
		leafID = folderID
	}

	return leafID, nil
}

// LinkDocument links a document to a folder via folder_documents.
func (r *FolderRepo) LinkDocument(ctx context.Context, folderID, documentID uuid.UUID) error {
	query := `INSERT INTO folder_documents (folder_id, document_id)
		VALUES ($1, $2)
		ON CONFLICT (folder_id, document_id) DO NOTHING`

	_, err := r.pool.Exec(ctx, query, folderID, documentID)
	if err != nil {
		return fmt.Errorf("folder repo: link document: %w", err)
	}
	return nil
}

// GetFolderByPath returns a folder by its unique path, or nil if not found.
func (r *FolderRepo) GetFolderByPath(ctx context.Context, path string) (*domain.Folder, error) {
	query := `SELECT id, name, parent_id, path, owner_class_library, owner_class_name, owner_id, is_auto_generated, created_at, updated_at
		FROM folders WHERE path = $1`

	var f domain.Folder
	err := r.pool.QueryRow(ctx, query, path).Scan(
		&f.ID, &f.Name, &f.ParentID, &f.Path,
		&f.OwnerClassLibrary, &f.OwnerClassName, &f.OwnerID,
		&f.IsAutoGenerated, &f.CreatedAt, &f.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("folder repo: get by path: %w", err)
	}
	return &f, nil
}

func (r *FolderRepo) ListRoots(ctx context.Context) ([]domain.Folder, error) {
	query := `SELECT id, name, parent_id, path, owner_class_library, owner_class_name,
		owner_id, is_auto_generated, created_at, updated_at
	FROM folders WHERE parent_id IS NULL ORDER BY name`
	return r.queryFolders(ctx, query)
}

func (r *FolderRepo) GetByID(ctx context.Context, id uuid.UUID) (*domain.Folder, error) {
	query := `SELECT id, name, parent_id, path, owner_class_library, owner_class_name,
		owner_id, is_auto_generated, created_at, updated_at
	FROM folders WHERE id = $1`

	var f domain.Folder
	err := r.pool.QueryRow(ctx, query, id).Scan(
		&f.ID, &f.Name, &f.ParentID, &f.Path, &f.OwnerClassLibrary, &f.OwnerClassName,
		&f.OwnerID, &f.IsAutoGenerated, &f.CreatedAt, &f.UpdatedAt,
	)
	if err == pgx.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("folder repo: get by id: %w", err)
	}
	return &f, nil
}

func (r *FolderRepo) GetChildren(ctx context.Context, parentID uuid.UUID) ([]domain.Folder, error) {
	query := `SELECT id, name, parent_id, path, owner_class_library, owner_class_name,
		owner_id, is_auto_generated, created_at, updated_at
	FROM folders WHERE parent_id = $1 ORDER BY name`
	return r.queryFoldersWithArg(ctx, query, parentID)
}

func (r *FolderRepo) GetDocuments(ctx context.Context, folderID uuid.UUID) ([]domain.Document, error) {
	query := `SELECT d.id, d.minio_bucket, d.minio_key, d.filename, d.content_type, d.file_size, d.sha256_hash,
		d.owner_id, d.owner_class_library, d.owner_class_name,
		d.attachment_type_id, d.attachment_type, d.is_external, d.legacy_file_id,
		d.current_version, d.created_by, d.created_at, d.updated_at, d.deleted_at
	FROM documents d
	JOIN folder_documents fd ON fd.document_id = d.id
	WHERE fd.folder_id = $1 AND d.deleted_at IS NULL
	ORDER BY fd.sort_order, d.filename`

	rows, err := r.pool.Query(ctx, query, folderID)
	if err != nil {
		return nil, fmt.Errorf("folder repo: get documents: %w", err)
	}
	defer rows.Close()

	var docs []domain.Document
	for rows.Next() {
		var doc domain.Document
		if err := rows.Scan(
			&doc.ID, &doc.MinioBucket, &doc.MinioKey, &doc.Filename, &doc.ContentType, &doc.FileSize, &doc.SHA256Hash,
			&doc.OwnerID, &doc.OwnerClassLibrary, &doc.OwnerClassName,
			&doc.AttachmentTypeID, &doc.AttachmentType, &doc.IsExternal, &doc.LegacyFileID,
			&doc.CurrentVersion, &doc.CreatedBy, &doc.CreatedAt, &doc.UpdatedAt, &doc.DeletedAt,
		); err != nil {
			return nil, fmt.Errorf("folder repo: scan document: %w", err)
		}
		docs = append(docs, doc)
	}
	return docs, rows.Err()
}

func (r *FolderRepo) Create(ctx context.Context, f *domain.Folder) error {
	if f.ID == uuid.Nil {
		f.ID = uuid.New()
	}
	query := `INSERT INTO folders (id, name, parent_id, path, owner_class_library, owner_class_name, owner_id, is_auto_generated)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8)`

	_, err := r.pool.Exec(ctx, query,
		f.ID, f.Name, f.ParentID, f.Path,
		f.OwnerClassLibrary, f.OwnerClassName, f.OwnerID, f.IsAutoGenerated,
	)
	if err != nil {
		return fmt.Errorf("folder repo: create: %w", err)
	}
	return nil
}

func (r *FolderRepo) Update(ctx context.Context, f *domain.Folder) error {
	query := `UPDATE folders SET name = $2, parent_id = $3, path = $4, updated_at = NOW()
		WHERE id = $1`
	ct, err := r.pool.Exec(ctx, query, f.ID, f.Name, f.ParentID, f.Path)
	if err != nil {
		return fmt.Errorf("folder repo: update: %w", err)
	}
	if ct.RowsAffected() == 0 {
		return fmt.Errorf("folder repo: update: not found")
	}
	return nil
}

func (r *FolderRepo) Delete(ctx context.Context, id uuid.UUID, cascade bool) error {
	if cascade {
		_, err := r.pool.Exec(ctx, `DELETE FROM folder_documents WHERE folder_id = $1`, id)
		if err != nil {
			return fmt.Errorf("folder repo: delete folder_documents: %w", err)
		}
		_, err = r.pool.Exec(ctx, `DELETE FROM folders WHERE parent_id = $1`, id)
		if err != nil {
			return fmt.Errorf("folder repo: delete children: %w", err)
		}
	}
	ct, err := r.pool.Exec(ctx, `DELETE FROM folders WHERE id = $1`, id)
	if err != nil {
		return fmt.Errorf("folder repo: delete: %w", err)
	}
	if ct.RowsAffected() == 0 {
		return fmt.Errorf("folder repo: delete: not found")
	}
	return nil
}

func (r *FolderRepo) queryFolders(ctx context.Context, query string) ([]domain.Folder, error) {
	rows, err := r.pool.Query(ctx, query)
	if err != nil {
		return nil, fmt.Errorf("folder repo: query: %w", err)
	}
	defer rows.Close()
	return scanFolders(rows)
}

func (r *FolderRepo) queryFoldersWithArg(ctx context.Context, query string, arg interface{}) ([]domain.Folder, error) {
	rows, err := r.pool.Query(ctx, query, arg)
	if err != nil {
		return nil, fmt.Errorf("folder repo: query: %w", err)
	}
	defer rows.Close()
	return scanFolders(rows)
}

func scanFolders(rows pgx.Rows) ([]domain.Folder, error) {
	var folders []domain.Folder
	for rows.Next() {
		var f domain.Folder
		if err := rows.Scan(
			&f.ID, &f.Name, &f.ParentID, &f.Path, &f.OwnerClassLibrary, &f.OwnerClassName,
			&f.OwnerID, &f.IsAutoGenerated, &f.CreatedAt, &f.UpdatedAt,
		); err != nil {
			return nil, fmt.Errorf("folder repo: scan: %w", err)
		}
		folders = append(folders, f)
	}
	return folders, rows.Err()
}
