package domain

import (
	"time"

	"github.com/google/uuid"
)

type Folder struct {
	ID                uuid.UUID
	Name              string
	ParentID          *uuid.UUID
	Path              string
	OwnerClassLibrary string
	OwnerClassName    string
	OwnerID           string
	IsAutoGenerated   bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}
